openapi: 3.0.0
info:
  description: |
    This is a delivery request server.
  version: "3"
  title: Delivery Requests Server
servers:
# Added by development team
# Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/Shivathanu/delivery-request/3
  - description: Delivery Requests service
    url: delivery api
tags:
  - name: Delivery Requests
    description: Everything about delivery requests
paths:
  /deliveryrequests:
    servers:
    - url: 'https://v25tmr7umf.execute-api.us-west-2.amazonaws.com/prod/'
    put:
      tags:
        - Delivery Requests
      description: 'Update a Delivery Requests'
      requestBody:
        description: Delivery Requests information
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeliveryRequests'
            example:
              DeliveryRequestId: '04b04dad-bd7b-409b-b131-ebbfbd1a5881'
      responses:
        '200':
          description: OK
          content:
            application/json:
              example:
                DeliveryRequestId: '04b04dad-bd7b-409b-b131-ebbfbd1a5881'
    post:
      tags:
        - Delivery Requests
      summary: Fetch all the delivery requests
      description: Creates the delivery request
      operationId: postDeliveryRequests
      responses:
        '405':
          description: Invalid input
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
      requestBody:
        $ref: '#/components/requestBodies/DeliveryRequests'
    get:
      tags:
        - Delivery Requests
      summary: Find delivery requests
      description: Returns all the delivery requests
      operationId: getDeliveryRequests
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid ID supplied
        '404':
          description: Delivery not found
  /deliveryrequests/{id}:
    servers:
    - url: 'https://v25tmr7umf.execute-api.us-west-2.amazonaws.com/prod/'
    parameters:
      - name: id
        in: path
        description: deliveryrequests ID
        required: true
        schema:
          type: string
          format: int64
    get:
      tags:
        - DeliveryRequests
      description: Get deliveryrequests by id
      responses:
        '200':
          description: OK
    delete:
      tags:
        - DeliveryRequests
      description: 'Delete a deliveryrequests'
      responses:
        '204':
          description: OK
          content:
            application/json:
              example:
components:
  schemas:
    DeliveryRequests:
      type: object
      properties:
        OrderId:
          type: integer
          format: int64
        ServiceId:
          type: integer
          format: int64
    ApiResponse:
      type: object
      properties:
        DeliveryRequestId:
          type: string
  requestBodies:
    DeliveryRequests:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DeliveryRequests'
          example:
            OrderId: 1
            ServiceId: 2
      description: Delivery object that needs to be added to the store
      required: true