openapi: 3.0.0
info:
  description: |
    This is a delivery request server.
  version: "3"
  title: Delivery Requests Server
servers:
# Added by development team
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/Arjun/delivery-request/3
  - description: Delivery Requests service
    url: delivery api
tags:
  - name: Delivery Requests
    description: Everything about delivery requests
paths:
  /deliveryrequests:
    servers:
    - url: 'https://v25tmr7umf.execute-api.us-west-2.amazonaws.com/prod/'
    post:
      tags:
        - Delivery Requests
      summary: Creates a delivery request
      description: Creates a delivery request using the input provided
      operationId: postDeliveryRequests
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '400':
          description: Invalid input
        '404':
          description: Not Found
      requestBody:
        $ref: '#/components/requestBodies/DeliveryRequests'
    get:
      tags:
        - Delivery Requests
      summary: Fetch delivery requests
      description: Returns all the delivery requests from the system
      operationId: getDeliveryRequests
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid input
        '404':
          description: Not Found
  /deliveryrequests/{id}:
    servers:
    - url: 'https://v25tmr7umf.execute-api.us-west-2.amazonaws.com/prod/'
    parameters:
      - name: id
        in: path
        description: ID of the Delivery Request
        required: true
        schema:
          type: string
          format: int64
    get:
      tags:
        - Delivery Requests
      summary: Get a Delivery Request by id
      description: Get delivery request by id
      operationId: getDeliveryRequestById
      responses:
        '200':
          description: OK
          content:
            application/json:
              example: { "success": true }
        '400':
          description: Invalid input
        '404':
          description: Not Found
    patch:
      tags:
        - Delivery Requests
      summary: Update a Delivery Request by id
      description: Update delivery request by id
      operationId: updateDeliveryRequestById
      responses:
        '200':
          description: OK
          content:
            application/json:
              example: { "success": true }
        '400':
          description: Invalid input
        '404':
          description: Not Found
      requestBody:
        $ref: '#/components/requestBodies/DeliveryRequests'
    delete:
      tags:
        - Delivery Requests
      summary: Delete a Delivery Request by id
      description: Delete a delivery request by id
      operationId: deleteDeliveryRequestById
      responses:
        '200':
          description: OK
          content:
            application/json:
              example: { "success": true }
        '400':
          description: Invalid input
        '404':
          description: Not Found
components:
  schemas:
    DeliveryRequests:
      type: object
      properties:
        OrderId:
          type: integer
          format: int64
        ServiceId:
          type: integer
          format: int64
        DeliveryDate:
          type: string
          example: "2000-01-01"
    ApiResponse:
      type: object
      properties:
        DeliveryRequestId:
          example: "04b04dad-bd7b-409b-b131-ebbfbd1a5881"
  requestBodies:
    DeliveryRequests:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DeliveryRequests'
          example:
            OrderId: 1
            ServiceId: 2
            DeliveryDate: "2000-01-01"
      description: Delivery object that needs to be added to the store
      required: true